### ISSUE TITLE
Stable version required by composer but none available

### ISSUE THREAD

**Issue by samtuke** [phpList/base-distribution#16]
### Short problem description
Composer fails to create the project due to lack of a stable version of this package

### Steps to reproduce
1. Execute ```$ composer create-project phplist/base-distribution```
2. Get error: ```[InvalidArgumentException] Could not find package phplist/base-distribution with stability stable.```

### Expected behaviour
Composer creates the project successfully

### Actual behaviour
Error printed

#### Package version
NA

#### PHP and Composer version
PHP 7.1.7 (cli) (built: Jul  6 2017 12:10:54) ( NTS )
Composer version 1.5-dev (27ee47def7648652615979e504d6bcc2e7f4bdef)

**Comment by oliverklee** [comment]
On it.
