### ISSUE TITLE
`list-modules` script prints two lines per module

### ISSUE THREAD

**Issue by samtuke** [phpList/base-distribution#44]
The composer script `list-modules` prints two lines per found module. Is this as intended? E.g.:

``` bash
$ composer run-script list-modules
> PhpList\PhpList4\Composer\ScriptHandler::listModules
phplist/phplist4-core  4.0.x-dev
phplist/phplist4-core  dev-master
phplist/rest-api       4.0.x-dev
phplist/rest-api       dev-master
```

**Comment by oliverklee** [comment]
No, this is not intentional, and also is not consistent with the way `composer show` works. I'll fix this.

**Comment by oliverklee** [comment]
https://github.com/phpList/phplist4-core/pull/186 fixes this.

**Comment by oliverklee** [comment]
Fixed.
