### ISSUE TITLE
/vendor/phplist/phplist4-core/vendor/autoload.php not found

### ISSUE THREAD

**Issue by samtuke** [phpList/base-distribution#45]
With a clean installation of the base distribution, running on the local PHP development server, the following error occurs when loading the index page in browser via http://127.0.0.1:8000/

```
[Sat Sep 30 12:16:31 2017] PHP Warning:  require(/var/www/base-dist/vendor/phplist/phplist4-core/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/base-dist/vendor/phplist/phplist4-core/web/app_dev.php on line 7
[Sat Sep 30 12:16:31 2017] PHP Stack trace:
[Sat Sep 30 12:16:31 2017] PHP   1. {main}() /var/www/base-dist/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Resources/router.php:0
[Sat Sep 30 12:16:31 2017] PHP   2. require() /var/www/base-dist/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Resources/router.php:42
```

**Comment by oliverklee** [comment]
This affects the development server (and probably the testing server), but not the production server.

We really need system tests to catch this kind of problem. (They already are on the to-do list for phase 2.)

**Comment by oliverklee** [comment]
The document root from the server:run command is incorrect. Looking into it.

**Comment by oliverklee** [comment]
`server:run --docroot=web/`works fine. I'm now trying to find out how we can get Symfony to automatically use the correct doc root.
